# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payments.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("payments.proto", :syntax => :proto3) do
    add_message "payments.BTCPaymentRequest" do
      optional :from_addr, :string, 1
      optional :to_addr, :string, 2
      optional :amount, :uint32, 3
    end
    add_message "payments.BTCPaymentResponse" do
      optional :successful, :bool, 1
      optional :message, :string, 2
    end
  end
end

module Payments
  BTCPaymentRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payments.BTCPaymentRequest").msgclass
  BTCPaymentResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payments.BTCPaymentResponse").msgclass
end
