# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: payments.proto for package 'payments'

require 'grpc'
require './lib/payments_pb'

module Payments
  module Bitcoin
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'payments.Bitcoin'

      rpc :SendPayment, ::Payments::BTCPaymentRequest, ::Payments::BTCPaymentResponse
    end

    Stub = Service.rpc_stub_class
  end
end
